* История и принципы деловых отношений

Формы регулирования поведения человека различны
К ним относят:
 - Правовые нормы
 - Традиции, обычаи
 - Привычки
 - Нормы морали и нравственности

Нарушение норм приводит к нормированному наказанию
Правовые нормы касаются только некоторых форм жизни человека

**Моральные нормы** - результат многовекового опыта человеческого общества,
которое всегда стремится к тому, чтобы каждый человек и общество в целом
могли гармонично сосуществовать

Нормы морали возникли как результат усилий человека разграничить добро и зло

Нормы морали отличаются от правовых тем, что они не зафиксированы в гос-венных
и международных документах

На нормах морали основаны традиции, обычаи, привычки

Традиции, которые базируются на нормах морали - основа формирования внешних
проявлений поведения и поступков человека

Черты, которые необходимы, используя современные деловые традиции

Изменения в гос устройстве, культуре, влияние техническог прогресса, развития
средств коммуникаций, все это влияет на традиции

Следование традициям позволяет проявить уважение к другим людям, к обычаям страны
к ее культуре

Правовые моральные нормы, традиции, обычаи, сходны по сути, причинам возникновения.
Иногда они отличаются друг от друга только формами проявления.

Вывод: устои жизни общества, вырвжвющиеся в различных формах - правовой, моральной,
традиционной - послужили основой той суммы норм, стандартов, рекомендаций, требований,
предъявляемых к поведению и поступкам людей, которую принято называть этикетом

В современном общ-ве практически все отношения подвластны нормам этикета
Родина этикета - Италия
Исторически этикет возник во дворцах

étiquette(фр) - манера, способ вести себя в общ-ве

Государственный этикет -> Дипломатический этикет
Одновременно развивается военный этикет. Поддерживает стройность и строгость правил
поведения в армии. Без него поряядок был бы невозможен
Светский этикет
Деловой этикет

**Манеры** - Отражают внутреннюю культуру человека, его истинное отношение к морали,
понимание моральных требований, его интеллект

Деловой этикет - внешнее выражение внутренней моральности и культурности человека

Принципы этикета:
   1) Здравый смысл
   2) Свобода. Принцип свободы ограничен здравым смыслом
   3) Этичность. Целиком и полностью этикет ориентирован на добро
   4) Удобство
   5) Целесообразность
   6) Экономичность. То, чем следует руководстводствоваться протокольному
      отделу организации
   7) Консерватизм. Надежность, фундоментальность, стабильность - черты в деловом мире
      привлекательные, имеющие содержательную связь с консерватизмом
   8) Непринужденность
   9) Универсализм
   10) Эффективность. Стандарты деловых отношений должны способствовать сокращению сроков
       испольнения договоров, заключению болшего числа договоров, уменьшению
       кол-ва вонфликтов в коллективе

Вывод: в конечном счет использование деловой этики экономически выгодно

ДЗ: "Функции и струкуры менеджмента организации"
Тема : "Планирование и прогнозирование как функции менеджмента"
План:
1) Функции в системе менеджмента
2) Прогнозирование в современных системах менеджмента
3) Планирование как функция менеджмента
4) Стратегическое планирование и управление
5) Бизнес планирование
      
